#!/usr/bin/env python

import sys

from gui.rqt_iris import MyPlugin
from gui.step import StepPlugin
from gui.pointInput import pointInputPlugin
from gui.RCDisplay import RCDisplayPlugin
from gui.utility import utilityPlugin
from gui.tabbedGUI import tabbedGUIPlugin
from gui.positionPlot import positionPlotPlugin
from gui.saver import saverPlugin
from rqt_gui.main import Main

plugin = 'gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
